// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/legacy/Chronicle.tsx": () => import("../components/mockups/legacy/Chronicle.tsx"),
  "./components/mockups/legacy/DynastyWall.tsx": () => import("../components/mockups/legacy/DynastyWall.tsx"),
  "./components/mockups/legacy/HallOfFame.tsx": () => import("../components/mockups/legacy/HallOfFame.tsx")
};
